version: '3.8'
services:
    db:
        image: postgres
        restart: always
        container_name: "postgresql"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: apidb
        volumes:
            - ./data:/var/lib/postgresql/data 
        ports:
            - "5432:5432"
    api:
        build: ./app
        volumes:
            - ./app:/app
        command: python3 ./app/manage.py runserver
        ports:
            - "8080:8080"
        depends_on:
            - db